<?php

namespace Fake;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-13 at 00:05:36.
 */
class FakeTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Fake
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Fake();
    }

    /**
     * @covers Fake\Fake::__toString
     */
    public function testToString() {
        $this->assertEquals(
            'Io sono Fake\Fake',
            "{$this->object}"
        );
    }

    /**
     * @covers Fake\Fake::testDependency
     */
    public function testTestDependency() {
        $this->assertEquals(
            'Fake Log',
            $this->object->testDependency()->getName()
        );
    }

}
