<?php

namespace Fake\Factory;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-01-10 at 23:58:39.
 */
class FakeFactoryTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var FakeFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FakeFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Fake\Factory\FakeFactory::getFake
     * @todo   Implement testGetFake().
     */
    public function testGetFake() {
        $this->assertEquals($this->object->getFake(), "Io sono " . \Fake\Fake::class);
    }

}
